import { LanguageKeys } from '../../languages';

const numberRange = (min: number, max: number) =>
  Array.from({ length: max - min + 1 }, (_, i) => min + i);

const Data: any = {
  appearanceAndHealth: [
    {
      title: LanguageKeys.height,
      data: [
        // ft values are total inches (4'0"–7'11"); the API only ever
        // receives cm (see profile-editor-flow buildScalingSelected).
        { scale: 'ft', values: numberRange(48, 95) },
        { scale: 'cm', values: numberRange(122, 250) },
      ],
      type: 'scalling',
      id: 'height',
      selected: { scale: 'ft' },
      category: 'appearance-0',
      apiKey: 'height',
    },
    // Weight slider intentionally removed — a numeric weight prompt clashes with
    // the welcome flow's empathy promise. Body type below (with "Prefer not to
    // say") is the optional, dignity-preserving descriptor that replaces it.
    // Height is kept.
    {
      title: LanguageKeys.disabilities,
      data: [],
      type: 'dropDown',
      id: 'dis-0',
      category: 'appearance-0',
      selected: {},
      apiKey: 'disability_id',
    },
    {
      title: LanguageKeys.bodyType,
      data: [],
      type: 'dropDown',
      id: 'bdy-0',
      selected: {},
      category: 'appearance-0',
      apiKey: 'body_type_id',
    },
    {
      title: LanguageKeys.eyesColor,
      data: [],
      type: 'dropDown',
      id: 'eye-0',
      selected: {},
      category: 'appearance-0',
      apiKey: 'eyes_color_id',
    },
    {
      title: LanguageKeys.skinTone,
      data: [],
      type: 'dropDown',
      id: 'skin-0',
      selected: {},
      category: 'appearance-0',
      apiKey: 'skin_tone_id',
    },
  ],
  familyBackground: [
    {
      title: LanguageKeys.ethinicity,
      data: [],
      type: 'dropDown',
      id: 'ethini-0',
      selected: {},
      category: 'familybg-0',
      apiKey: 'ethinicity_id',
    },
    {
      title: LanguageKeys.language,
      data: [],
      type: 'dropDown',
      id: 'language',
      selected: {},
      category: 'familybg-0',
      apiKey: 'language',
    },
    {
      title: LanguageKeys.nationality,
      data: [],
      type: 'dropDown',
      id: 'nationality',
      selected: {},
      category: 'familybg-0',
      apiKey: 'nationality',
    },
    {
      title: LanguageKeys.caste,
      placeholder: 'Enter caste',
      data: [],
      id: 'caste',
      type: 'input',
      selected: {},
      category: 'familybg-0',
      apiKey: 'caste',
    },
  ],
  lifeStyle: [
    {
      title: LanguageKeys.educationLevel,
      data: [],
      type: 'dropDown',
      id: 'edu-0',
      selected: {},
      category: 'life-0',
      apiKey: 'education_level_id',
    },
    {
      title: LanguageKeys.profession,
      data: [],
      type: 'dropDown',
      id: 'prof-0',
      selected: {},
      category: 'life-0',
      apiKey: 'profession_id',
    },
    {
      title: LanguageKeys.earningsPerMonth,
      data: [],
      type: 'dropDown',
      id: 'earn-0',
      selected: {},
      category: 'life-0',
      apiKey: 'earnings_per_month_id',
    },
    {
      title: LanguageKeys.maritalStatus,
      data: [],
      type: 'dropDown',
      id: 'martial-0',
      selected: {},
      category: 'life-0',
      apiKey: 'maritial_status_id',
    },
    {
      title: LanguageKeys.haveChildren,
      viewTitle: LanguageKeys.children,
      data: [
        { id: LanguageKeys.yes, value: 1 },
        { id: LanguageKeys.no, value: 0 },
      ],
      type: 'dropDownBinary',
      id: 'haveChildren',
      selected: {},
      category: 'life-0',
      apiKey: 'have_children',
    },
    {
      title: LanguageKeys.doYouSmoke,
      viewTitle: LanguageKeys.smokingLabel,
      data: [],
      type: 'dropDown',
      id: 'smoke-0',
      selected: {},
      category: 'life-0',
      apiKey: 'smoking_id',
    },
    {
      title: LanguageKeys.doYouDrink,
      viewTitle: LanguageKeys.drinking,
      data: [],
      type: 'dropDown',
      id: 'drink-0',
      selected: {},
      category: 'life-0',
      apiKey: 'drinking_id',
    },
    {
      title: LanguageKeys.doYouOwnACar,
      viewTitle: LanguageKeys.car,
      data: [
        { id: LanguageKeys.yes, value: 1 },
        { id: LanguageKeys.no, value: 0 },
      ],
      type: 'dropDownBinary',
      id: 'doYouOwnACar',
      selected: {},
      category: 'life-0',
      apiKey: 'have_car',
    },
    {
      title: LanguageKeys.doYouOwnABusiness,
      viewTitle: LanguageKeys.business,
      data: [
        { id: LanguageKeys.yes, value: 1 },
        { id: LanguageKeys.no, value: 0 },
      ],
      type: 'dropDownBinary',
      id: 'doYouOwnABusiness',
      selected: {},
      category: 'life-0',
      apiKey: 'have_business',
    },
    {
      title: LanguageKeys.doYouKeepPets,
      viewTitle: LanguageKeys.pets,
      data: [
        { id: LanguageKeys.yes, value: 1 },
        { id: LanguageKeys.no, value: 0 },
      ],
      type: 'dropDownBinary',
      id: 'doYouKeepPets',
      selected: {},
      category: 'life-0',
      apiKey: 'have_pets',
    },
    {
      title: LanguageKeys.doYouOwnAHouse,
      viewTitle: LanguageKeys.house,
      data: [
        { id: LanguageKeys.yes, value: 1 },
        { id: LanguageKeys.no, value: 0 },
      ],
      type: 'dropDownBinary',
      id: 'doYouOwnAHouse',
      selected: {},
      category: 'life-0',
      apiKey: 'have_house',
    },
  ],
  waliInformation: [
    {
      title: LanguageKeys.firstName,
      placeholder: LanguageKeys.notYetProvided,
      data: [],
      type: 'input',
      id: 'firstName',
      selected: {},
      category: 'wali-0',
      apiKey: 'wali_first_name',
    },
    {
      title: LanguageKeys.lastName,
      placeholder: LanguageKeys.notYetProvided,
      data: [],
      type: 'input',
      id: 'lastName',
      selected: {},
      category: 'wali-0',
      apiKey: 'wali_last_name',
    },
    {
      title: LanguageKeys.phoneNumber,
      placeholder: LanguageKeys.notYetProvided,
      data: [],
      type: 'input',
      id: 'phoneNumber',
      selected: {},
      category: 'wali-0',
      apiKey: 'wali_phone',
    },
    {
      title: LanguageKeys.email,
      placeholder: LanguageKeys.notYetProvided,
      data: [],
      type: 'input',
      id: 'email',
      selected: {},
      category: 'wali-0',
      apiKey: 'wali_email',
    },
  ],
  islamicValues: [
    {
      title: LanguageKeys.howMuchDoYouPray,
      viewTitle: LanguageKeys.prayerLabel,
      data: [],
      type: 'dropDown',
      id: 'pray-0',
      selected: {},
      category: 'islamicval-0',
      apiKey: 'prayers_punctuality_id',
    },
    {
      title: LanguageKeys.doYouCoverYourself,
      viewTitle: LanguageKeys.hijabLabel,
      data: [],
      type: 'dropDown',
      id: 'hijab-0',
      selected: {},
      category: 'islamicval-0',
      apiKey: 'hijab_level_id',
    },
    {
      title: LanguageKeys.doYouHaveABeard,
      viewTitle: LanguageKeys.beard,
      data: [
        { id: LanguageKeys.yes, value: 1 },
        { id: LanguageKeys.no, value: 0 },
      ],
      type: 'dropDownBinary',
      id: 'doYouHaveABeard',
      selected: {},
      category: 'islamicval-0',
      apiKey: 'have_beard',
    },
    {
      title: LanguageKeys.overallPracticeLevel,
      data: [],
      type: 'dropDown',
      id: 'islam-0',
      selected: {},
      category: 'islamicval-0',
      apiKey: 'islamic_practice_level_id',
    },
    {
      title: LanguageKeys.sect,
      data: [],
      type: 'dropDown',
      id: 'sect-0',
      selected: {},
      category: 'islamicval-0',
      apiKey: 'sect_id',
    },
    {
      title: LanguageKeys.muslimType,
      data: [
        { id: LanguageKeys.yes, value: 1 },
        { id: LanguageKeys.no, value: 0 },
      ],
      type: 'dropDownBinary',
      id: 'muslim-0',
      selected: {},
      category: 'islamicval-0',
      apiKey: 'is_new_muslim',
    },
  ],
  personalityRequirements: [
    {
      title: LanguageKeys.aboutYourself,
      viewTitle: LanguageKeys.aboutView,
      placeholder: LanguageKeys.notYetProvided,
      data: [],
      type: 'input',
      id: 'aboutYourself',
      selected: {},
      category: 'personality-0',
      apiKey: 'about_you',
    },
    {
      title: LanguageKeys.aboutPartner,
      viewTitle: LanguageKeys.lookingFor,
      placeholder: LanguageKeys.notYetProvided,
      data: [],
      type: 'input',
      id: 'aboutPartner',
      selected: {},
      category: 'personality-0',
      apiKey: 'about_partner',
    },
    {
      title: LanguageKeys.likes,
      placeholder: LanguageKeys.notYetProvided,
      data: [],
      type: 'input',
      id: 'likes',
      selected: {},
      category: 'personality-0',
      apiKey: 'likes',
    },
    {
      title: LanguageKeys.disLikes,
      placeholder: LanguageKeys.notYetProvided,
      data: [],
      type: 'input',
      id: 'disLikes',
      selected: {},
      category: 'personality-0',
      apiKey: 'dislikes',
    },
    {
      title: LanguageKeys.openForPolygamy,
      data: [
        { id: LanguageKeys.yes, value: 1 },
        { id: LanguageKeys.no, value: 0 },
      ],
      type: 'dropDownBinary',
      id: 'openForPolygamy',
      selected: {},
      category: 'personality-0',
      apiKey: 'open_for_polygamy',
    },
  ],
  futurePlan: [
    {
      title: 'What are your plans for having children?',
      viewTitle: LanguageKeys.familyPlans,
      data: [],
      type: 'dropDown',
      id: 'familyplan-0',
      selected: {},
      category: 'futureplan-0',
      apiKey: 'family_plan_id',
    },
    {
      title: 'When do you plan to get married?',
      viewTitle: LanguageKeys.marriageTimeline,
      data: [],
      type: 'dropDown',
      id: 'marriageplan-0',
      selected: {},
      category: 'futureplan-0',
      apiKey: 'marriage_plan_id',
    },
    {
      title: 'Are you open to relocating?',
      viewTitle: LanguageKeys.openToRelocating,
      data: [],
      type: 'dropDown',
      id: 'relocationplan-0',
      selected: {},
      category: 'futureplan-0',
      apiKey: 'relocation_plan_id',
    },
  ],
};

export default Data;
